/**
 * @author yz
 * @date 2019/8/12
 * @Description:
 */

var titleArrs = ['新闻列表', '智慧专题应用', '基础平台', '' ,'标准体系']
var htmlData = [
    [],
    [
        {
            title:'智慧建管',
            desc:'实现对工程项目事件进行统一管理，提供高效智慧化服务',
            url:'www.baidu.com',
            img:'zhjg.png'
        },
        {
            title:'智慧城管',
            desc:'提供行政执法事件的信息化服务',
            url:'www.baidu.com',
            img:'zhcg.png'
        },
        {
            title:'智慧环保',
            desc:'提供环境综合监控平台服务',
            url:'www.baidu.com',
            img:'zhhb.png'
        },
        {
            title:'智慧社区',
            desc:'实现社区数据、信息、管理、服务的整体融合',
            url:'www.baidu.com',
            img:'zhsq.png'
        }
    ],
    [
        {
            title:'城市运行管理平台',
            desc:'城市运行态势的全面感知、科学预防、高效处置、智慧决策和集约共享',
            url:'www.baidu.com',
            img:'csyxglpt.png'
        },
        {
            title:'数据共创平台',
            desc:'面向社会共创提供服务，以聚合数据、服务资源为基础，协助政府完成数据的开放、创新、流通以及双创成果转化，构建大数据产业共创生态',
            url:'www.baidu.com',
            img:'sjgcpt.png'
        },
        {
            title:'物联网管理平台',
            desc:'统一城市平台感知数据采集与汇聚，统一平台管理与监控，构筑城市感知网元服务体系',
            url:'www.baidu.com',
            img:'wlwglpt.png'
        }
    ]
]
var sjzsData = [
    [
        {
            title:'数据共享服务平台',
            desc:'依据国家和新区共享标准体系，提供政务信息资源数据共享服务',
            url:'www.baidu.com',
            img:'sjfw/sjgzfwpt.png'
        },
        {
            title:'数据开放平台',
            desc:'依据国家和新区开放标准体系，面向社会公众提供数据开放服务',
            url:'www.baidu.com',
            img:'sjfw/sjkfpt.png'
        },
        {
            title:'数据活化服务平台',
            desc:'提供API和微应用生成与管理功能，提高数据使用率和数据价值',
            url:'www.baidu.com',
            img:'sjfw/sjhhfwpt.png'
        },
    ],
    [
        {
            title:'元数据管理平台',
            desc:'提供基础元数据的维护与管理',
            url:'www.baidu.com',
            img:'sjzlgl.png'
        },
        {
            title:'数据质量管理平台',
            desc:'提供ETL过程和基础库数据的质量管控',
            url:'www.baidu.com',
            img:'sjzlgl.png'
        }
    ],
    [
        {
            title:'信息资源梳理系统',
            desc:'构建新区政务信息资源目录体系，摸清家底',
            url:'www.baidu.com',
            img:'zyml/xxzyslxt.png'
        },
        {
            title:'资源目录管理系统',
            desc:'管理新区各委办局已梳理的信息资源目录，包括数据、文件和API',
            url:'www.baidu.com',
            img:'zyml/zymlglxt.png'
        },
        {
            title:'资源目录可视化系统',
            desc:'展示新区全域内信息资源目录的情况',
            url:'www.baidu.com',
            img:'zyml/zymlkshxt.png'
        }
    ],
    [
        {
            title:'数据通',
            desc:'实现新区各部门数据资产的开采与服务能力',
            url:'www.baidu.com',
            img:'sjt/sjt.png'
        },
        {
            title:'数据交换平台',
            desc:'实现从委办局交换数据，经过ETL过程并写入新区大数据中心基础库',
            url:'www.baidu.com',
            img:'sjt/sjjhpt.png'
        },
        {
            title:'ESB',
            desc:'高效稳定、灵巧开放的企业服务总线中间件',
            url:'www.baidu.com',
            img:'sjt/ESB.png'
        }
    ],
    [
        {
            title:'PaaS平台',
            desc:'提供高度自动化的运维管理平台',
            url:'www.baidu.com',
            img:'jczcyfw/PaaS.png'
        },
        {
            title:'安全认证',
            desc:'提供统一的安全认证机制，保证用户安全，数据安全',
            url:'www.baidu.com',
            img:'jczcyfw/aqrz.png'
        },
        {
            title:'内容管理',
            desc:'内容采集、编辑、审核和基于模板的动态内容变更和实时静态内容发布',
            url:'www.baidu.com',
            img:'jczcyfw/nrgl.png'
        },
        {
            title:'消息通知',
            desc:'实现信息的交换、路由、分发、流程定义等功能',
            url:'www.baidu.com',
            img:'jczcyfw/xxtz.png'
        },
        {
            title:'工作流',
            desc:'提供工作流设计，流程部署与运行等功能',
            url:'www.baidu.com',
            img:'jczcyfw/gzl.png'
        },
        {
            title:'GIS',
            desc:'提供新一代三维GIS技术，包括全新连续空间的三维数据模型',
            url:'www.baidu.com',
            img:'jczcyfw/GIS.png'
        },
        {
            title:'3D可视化',
            desc:'提供全功能三维“零客户端”，支持开放的三维数据规',
            url:'www.baidu.com',
            img:'jczcyfw/3D.png'
        }
    ],
    [
        {
            title:'数据湖',
            desc:'互联网、物联网和政务网数据的汇聚',
            url:'www.baidu.com',
            img:'iconsjh.png'
        }
    ]
]

var xwzxSwiperData = [
        {
            img:'图层2.png',
            url:'http://wwww.baidu.com',
            content:'3月19日，长春新区召开扫黑除恶专项斗争长春新区召开扫黑除恶专项斗争领导小组会议暨省市督导领导小组会议暨省市督导检查反馈意见整改落实、“一案一整治”工作部署及配合做好中央督导检查工作会议，深入贯彻落实全市扫黑除恶专项斗争工作推进...'
        },
        {
            img:'bg2.jpg',
            url:'http://wwww.baidu.com',
            content:'一切都是命运石之门的选择'
        },
        {
            img:'gl7.jpg',
            url:'http://wwww.baidu.com',
            content:'钢之炼金术士'
        }
]